AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:

  ExecutionRoleByCF:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: venv/lib/python3.6/dist-packages
      Handler: ExecutionRoleByCF_function.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::267681339347:role/AdminRole'
      Runtime: python3.7
      Timeout: 60
      
  StackSetInstances:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: venv/lib/python3.6/dist-packages
      Handler: StackSetInstances_function.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::267681339347:role/AdminRole'
      Runtime: python3.7
      Timeout: 60